#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "ssh_apprise"
name = "SSH Apprise"
description.en = "Get notified of any SSH connection with Apprise"
description.fr = "Notification de connexions SSH avec Apprise"

version = "1.9.6~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "BSD-2-Clause"
admindoc = "https://github.com/caronc/apprise/wiki"
code = "https://github.com/caronc/apprise"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.information]
    ask.en = "This utility can be configured from its configuration panel in the YunoHost webadmin."
    ask.fr = "Cet utilitaire peut être configuré depuis son panneau de configuration dans la webadmin de YunoHost"
    type = "markdown"

[resources]

    [resources.sources]

    # Dummy resource to trigger version updates
    [resources.sources.main]
    prefetch = false
    url = "https://github.com/caronc/apprise/archive/refs/tags/v1.9.6.tar.gz"
    sha256 = "877fbf1c2de4a6168baa555bf572fa27ed61f7d6c74662bc32c1acdc660847e1"
    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.apt]
    packages = "python3, python3-pip, python3-venv"
